### ISSUE TITLE
refactor: Aardvark & SDOH schema to single object

### ISSUE THREAD

**Issue by mradamcox** [healthyregions/SDOHPlace#115]
In a few places, both the Aardvark schema and our extra SDOH schema are loaded as individual JSON objects, and then passed into functions like`findSolrAttributes` for interrogation. It would be better to have a single helper method that loaded and combined any `.json` files inside of `src/pages/search/_metadata` and returned a combined object. Then functions like `findSolrAttributes` would only take a single `schema: {}` argument, instead of the current two `aardvark_json: {}, sdoh_json: {}` arguments.

**Comment by mradamcox** [comment]
Yes, and the top-level ids will be unique across all files. This isn't urgent at all, more of a small detail, just wanted to write it down while I was thinking about it.

**Comment by pengyin-shan** [comment]
Ok, I'll work on this

**Comment by pengyin-shan** [comment]
Close this issue as the code has been merged
