### ISSUE TITLE
Navbar Updates (hamburger menu)

### ISSUE THREAD

**Issue by mradamcox** [healthyregions/SDOHPlace#16]
A few things need to happen to the navbar still:

- [x] add links
- [x] add style for active pages (see design)
- [x] set width to match figma design (seems like 1068px wide is the max? this is especially clear on the subpages, not homepage)
- [x] move component out of homepage directory? not super necessary but may make sense.

**Comment by mukeshchugani10** [comment]
One more task based on my discussion with Shubham:

- [ ] The navbar in mobile view (hamburger menu) needs to be designed and implemented.

**Comment by mradamcox** [comment]
Currently the mobile menu looks like this:
![image](https://github.com/healthyregions/SDOHPlace/assets/10427268/dafbfd89-2af9-4c68-b7ca-7f6bde042e8d)

@shubham Are there any simple changes we could make to satisfy this ticket? If you want to wait and spend more time on a redesign that's no problem, just wanted to check in.

**Comment by shubhamk008** [comment]
Let's make the text white, that should be sufficient for now.
