### ISSUE TITLE
Change blog post hyperlinks to violet

### ISSUE THREAD

**Issue by shubhamk008** [healthyregions/SDOHPlace#229]
To make the blog post links from default blue to French Violet, which is our brand color (#7E1CC4).

**Comment by mradamcox** [comment]
@shubhamk008 I've done this now. However, I'm looking at links elsewhere on the site and they do not match up, and I'd like to fix them while I finish this ticket.

In the Figma designs, this is the only example of an inline link that I can see:
![image](https://github.com/user-attachments/assets/e71c5c71-8208-4953-9208-9e26c97a715a)
Which raises a couple other questions: Does it change color on hover? Does it change color after being visited?
We have french violet on a different page:
![image](https://github.com/user-attachments/assets/9a4232eb-3726-4bf9-ba90-23474b671121)
Which turns to this blue on hover:
![image](https://github.com/user-attachments/assets/246b92c4-db00-478c-b323-b214bb63ba65)

Can you let me know what we should be using across the board?
