### ISSUE TITLE
"No results" on discovery app needs to be adjust to fix the new UI

### ISSUE THREAD

**Issue by pengyin-shan** [healthyregions/SDOHPlace#264]
Currently the old "No results" view is still being used. Need to adjust this to fit the new UI

**Comment by mradamcox** [comment]
![image](https://github.com/user-attachments/assets/a660beaf-06fe-4e9a-a7b9-881fe0bd08f6)

We can put placeholder tags in for the theme searches for now, we will connect them once we have that field ready to be filtered.
