### ISSUE TITLE
apply basic toolkit styles to Guide layout

### ISSUE THREAD

**Issue by mradamcox** [healthyregions/SDOHPlace#326]
We need to add styling to the layout that is used for the new Guides, and for this we will use the styles that are already in the SDOH & Place toolkit. Codebase (with CSS styles) for the toolkit is here, https://github.com/healthyregions/sdohplace-toolkit, and the published toolkit is here: https://toolkit.sdohplace.org

Specifically, we need to be replicating

- [x] All header styles
- [x] List styles
    ![image](https://github.com/user-attachments/assets/68b3b043-aea3-4a25-be04-38530f03076e)
- [x] `<detail>`/`<summary>` elements
    ![image](https://github.com/user-attachments/assets/294ba600-e246-4edb-8717-593f6851850e)
- [ ] Table styles
    ![image](https://github.com/user-attachments/assets/af4c6650-3362-4a4c-a685-9c30396fc24b)

Things we don't need to worry about for this ticket:

- Callout boxes (we'll do these later)
- Permalinks in headers (Bookdown auto-generates these in the toolkit, and we don't need to replicate that behavior at this time)

**Comment by shubhamk008** [comment]
Also require:
- [ ] Styles for links
- [ ] Styles for image captions

**Comment by mradamcox** [comment]
One other note: For now these styles should be scoped just to this one template, but eventually we'll look at applying them to other content on the website as well (like news items, showcases, etc).
