### ISSUE TITLE
Search Platform Architecture Refactoring Tasks

### ISSUE THREAD

**Issue by pengyin-shan** [healthyregions/SDOHPlace#391]
Our current code has reached a stage where a review of all features and some refactoring are necessary to accommodate upcoming requests. This process is expected to conclude by early December, although we can still add new features during this period based on user feedback.

### Current Pain Points

1. URL state synchronization delays causing race conditions with Solr queries
2. Tightly coupled component logic making code maintenance difficult
3. Complex state management spread across components
4. Limited separation of concerns between UI and data layers

### Objectives

- [ ]  Separate API layer from UI components
- [ ]  Implement centralized state management
- [ ]  Improve error handling and loading states
- [ ]  Create a *hashed* URL sharing functionality

### Steps

- [x] #392
- [x] #393
- [x] #394
- [x] #395

**Comment by mradamcox** [comment]
Sorry for being late to comment on this, but I'd like to add just a few more specifics here.

First, here is what I was thinking that we would be able to do (simplified), where `nuqs` is the manager of URL params, and any UI component would only be pushing values to those params. Whenever the params changed, watched by `nuqs`, then a single function would generate the solr query from these params and make the request to solr.
![image](https://github.com/user-attachments/assets/8b0b5ea9-aa55-4f3b-aaab-4ba1f6702e36)
<details>
<summary>d2 diagram code</summary>

```
grid-rows: 2

url

d: "" {
  grid-gap: 20
  grid-columns: 2
}
d.q: query constructor
d.s: solr search\nrequest
d.c: UI\ncomponents

url -> d.q

d.q -> d.s
url <- d.c
```

</details>

However, given the delays @pengyin mentions above, it seems like this is too simplistic and we can't rely on the URL as the core state manager. So we need something more like what is show below, with an internal state manager being fed changes from the UI, and then dispatching those changes, essentially as before, to a single place that the solr query is constructed and submitted.

![image](https://github.com/user-attachments/assets/adc181f7-fc50-406c-ae7b-6dce7148fd08)
<details>
<summary>d2 diagram code</summary>

```
grid-rows: 2

url

d: "" {
  grid-gap: 20
  grid-columns: 3
}
d.q: query constructor
d.s: solr search\nrequest
d.ss: state\nmanager
d.c: UI\ncomponents

d.ss -> d.q

d.q -> d.s
d.ss <- d.c

url -> d.ss
d.ss -> url

```

</details>

@pengyin-shan can you let me know if we are on the same page with this concept? I realize this is still simplistic and doesn't necessarily account for the separate request that needs to be made of the extra "you may be interested in" search results, but hopefully it's close?

Finally, I wanted to check about the hashed URL: can you explain the need for that again?

**Comment by pengyin-shan** [comment]
Hi @mradamcox,

Thank you for the feedback! Let me clarify:

1. Yes, the state manager is the core, not the URL. The URL is simply one input/output of our state system. Here's how it works:

- State Manager (Redux): Central source of truth, handling all state updates
- Query Constructor: A pure function service that builds Solr queries based on state
- URL Manager: Handles encoding/decoding state to/from the URL

The flow is as follows:

- The UI triggers an action → Updates the Redux state
- A state change → Triggers query construction and search
- A state change → Updates the URL hash (without triggering a new search)

An example could be:
``` javascript
// very draft version
export default function SearchPage() {
  const dispatch = useDispatch()
  const router = useRouter()
  useEffect(() => {
    if (router.isReady) {
      dispatch(initializeFromUrl(window.location.href))
        .unwrap()
        .then(() => {
          // search only after the state is initialized, this way we can prevent the previous issue of the search finishes before all URL parameters are collected
          dispatch(executeSearch())
        })
    }
  }, [router.isReady])
```

2. My goal is to hide the URL structure from regular users to avoid confusion caused by long URLs and prevent issues if users attempt to manipulate them (e.g., changing parameters that could cause the page to crash awkwardly). By using a hashing approach, we can:

- Prevent URL parameter manipulation that might break the app
- Make long URLs more manageable (especially with complex geometry)
- Keep the state serialization format internal
- Simplify versioning of our URL format, if needed

Example for `/search?state=eyJxIjoicGFya3MiLCJnIjoiUE9MWUdPTigoMzAgMTAsNDAgNDAsMjAgNDAsMTAgMjAsMzAgMTApKSJ9`:
```javascript
// all 404 state could be in one location and use a unified way of handling, so we don't need to prepare for special case for each possiblilty of breaking the url
export function decodeUrlStateWithValidation(url: string): DecodedState {
  try {
    const searchParams = new URLSearchParams(url.split('?')[1]) // we can change to nuqs if we like
    const hashState = searchParams.get('state')
    if (!hashState) {
      throw new Error('No state parameter found in URL'); // now the page could be a '404' state
    }
    const decodedString = decode(hashState)
    const decodedState = JSON.parse(decodedString)
    if (typeof decodedState !== 'object') {
      throw new Error('Invalid state format');  // now the page could be a '404' state
    }
    if (decodedState.g && !isValidGeometry(decodedState.g)) {
      throw new Error('Invalid geometry format');  // now the page could be a '404' state
    }
    return {
      query: validateString(decodedState.q),
      geometry: validateString(decodedState.g),
      filters: validateArray(decodedState.f),
      //... other page states
    }
  } catch (error) {
    console.error('URL state decode error:', error);  // now the page could be a '404' state
    return {
      query: '',
      geometry: '',
      filters: []
    }
  }
}
```

I am doing some initial transformations to the existing code, let me know your thoughts!

**Comment by mradamcox** [comment]
1. Sounds great, thanks for the extra details. Looking forward to seeing how this comes along!
2. Overall, I'm not convinced that this change is beneficial, and I would like to stay with plain-text URL params for now. Here's why:
    - If the URL is obfuscated, it is more difficult to inspect and test during development
    - If the URL is obfuscated, it will still break if a character is missing/miscopied, but it will break in a less obvious way
    - Sensible defaults and basic validation can be applied when reading each URL param such that the state is not broken by a malformed URL (this should be an underlying principle of the design anyway)
    - There is no real issue with URL length, as the only geometry we have in the URL is the bounding box, which will always be the same number of characters

**Comment by pengyin-shan** [comment]
@mradamcox, I am still concerned about the URL length because we have added (and will continue to add) many statuses to it. Currently, it includes at least four filters (spatial resolution, year, sort, theme), spatial-related information, showFilters status, showDetailPanel status, item ID, and query terms. In the future, we may need to add more filters, user settings (like user ID and user status), etc.

This could make the URL extremely long and difficult to manage. Users might see three to four lines of URL in the 'Share' box:
<img width="1198" alt="Screenshot 2024-11-25 at 11 48 06 AM" src="https://github.com/user-attachments/assets/b935bdf4-adc3-4862-8958-12a735b2fd9a">

With such a long URL, users are more likely to encounter issues if they copy and paste it from the address bar. For example, they might accidentally copy only the visible portion of the URL in their browser, which would result in an incomplete link.

If you prefer to stick with pure URLs, we can certainly proceed that way. However, I would recommend considering a multi-page method for pure URLs to distribute the parameters across multiple pages, thereby reducing the burden on a single page. This would involve a more significant change, so it’s just an option to keep in mind. Alternatively, we could hash the content of the parameters (such as long titles) to shorten the URL somewhat.

**Comment by mradamcox** [comment]
Ok, user settings should not be in the URL, so don't worry about that. And now that the URL will not drive everything on the page, like before, we will already be able to remove some of what we have. Further, we can shorten the parameter names. Let's move this discussion to https://github.com/healthyregions/SDOHPlace/issues/395 so we can take a more holistic planning approach to planning this.

**Comment by pengyin-shan** [comment]
Close this PR as the refactoring for this stage has been completed. As more features are introduced, we can continue optimizing along the way.
