### ISSUE TITLE
Home page updates

### ISSUE THREAD

**Issue by mradamcox** [healthyregions/SDOHPlace#46]
- [x]  Hyperlink to our lab and UIUC in the “brought to you by section”
- [x]  Remove “have a spatial footprint” in the SDOH banner
- [ ]  Make sure the main text size is consistent (it currently differs in the SODH section, blog, and others)
- [x]  Add “including open-source GIS tools” in the toolkit description
- [x]  Github icon should go to the specific repo of the project (this repo)
- [x]  Hyperlink Image & Title in recent news section
- [x] Re-order blog posts so the intro comes first (on the left)

**Comment by mukeshchugani10** [comment]
Some more tasks based on my discussion with Shubham:

- [ ] Footer to be restricted to a max width of 1536px (just like the hero part). The dots and dashes will still be fixed to the edges of the screen but the content will be restricted to a max width.
- [ ] The buttons in the hero part don't need to change color on hover. Instead, add a box shadow on hover.
- [ ] It might be good to have the data discovery and community toolkit buttons in the "Access data & resources" section and have them greyed out (not clickable).

**Comment by theashwin** [comment]
Pushed to main, tested on dev. Left font consistency for you as don't know which one is the ideal size.

**Comment by mradamcox** [comment]
Adding one more task to this:

- [ ] on mobile, stack logos vertically instead of horizontally

**Comment by pengyin-shan** [comment]
> Adding one more task to this:
> 
> * [ ]  on mobile, stack logos vertically instead of horizontally

This has been handled in #125

**Comment by mradamcox** [comment]
Closing in favor of new design-related tickets.
