### ISSUE TITLE
Dynamically pull blog posts to home page

### ISSUE THREAD

**Issue by mradamcox** [healthyregions/SDOHPlace#48]
Currently, links and description text are hardcoded into the homepage. This should be updated to pull a live list from the files in the posts directory. Code in the news list page will have a good example of how to do this.

More importantly, this will require the creation of two new properties on each post:
- [x] Description: where the post writer will add the first 25 words (plus an ellipses) to be shown on the home page
- [x] Featured Image: this image doesn't have to be integrated into the post itself (that's a different discussion) but it will be used for the thumbnail on the homepage. Maybe name this property "thumbnail image?"

**Comment by mradamcox** [comment]
This config file is what defines the properties that each post can have: https://github.com/healthyregions/SDOHPlace/blob/main/public/admin/config.yml

It's where the description and header image should be added.

**Comment by theashwin** [comment]
Code pushed to **main**. Pending prod testing.

**Comment by mradamcox** [comment]
All set and deployed now. Posts now have these two new required properties. The Feature Image and the Excerpt are what gets displayed on the home page.

![image](https://github.com/healthyregions/SDOHPlace/assets/10427268/9c813de9-b75b-49c8-bc0f-fe1ac6d901b4)
