### ISSUE TITLE
Filter for search result

### ISSUE THREAD

**Issue by pengyin-shan** [healthyregions/SDOHPlace#88]
For now, add filters to filter search results as what we have in http://52.14.175.140:3000/

- [ ] #97

**Comment by mradamcox** [comment]
One filter we need for sure will be on the Spatial Resolution (`spatial_resolution`) field. Something as simple as this would work for now:
![image](https://github.com/healthyregions/SDOHPlace/assets/10427268/5a04ecde-1d3f-4b14-85fc-371f5f6b7b1a)

When a user clicks one of the facets values, the parent record list should update to only show those with the corresponding value.

**Comment by pengyin-shan** [comment]
Close this issue as the code has been merged
